runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /edit
  script: edit.application
  login: required

- url: /delete
  script: delete.application
  login: required

- url: /upload
  script: upload.application
  login: required

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
