runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /js
  static_dir: static/js
- url: /bootstrap
  static_dir: static/bootstrap
- url: /
  static_files: templates/index.html
  upload: templates/index\.html
  secure: always
- url: /_ah/spi/.*
  script: main.api
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: 2.6
- name: endpoints
  version: 1.0

env_variables:
  FIREBASE_PROJECT_ID: 'wessex-saxonics'
