runtime: python27
api_version: 1
threadsafe: true
service: backend 

handlers:
- url: /_ah/spi/.*
  script: main.api
  secure: always

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: latest
- name: endpoints
  version: latest

env_variables:
  ENDPOINTS_SERVICE_NAME: backend.wessex-saxonics.appspot.com
  ENDPOINTS_SERVICE_VERSION: 2016-12-30r0
