runtime: python27
api_version: 1
threadsafe: true
service: backend

handlers:
- url: /_ah/api/.*
  script: main.api
  secure: always

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: latest

env_variables:
  ENDPOINTS_SERVICE_NAME: backend-dot-wessex-saxonics.appspot.com
  ENDPOINTS_SERVICE_VERSION: 2017-01-08r10
  FIREBASE_PROJECT_ID: 'wessex-saxonics'
